use serde::{Deserialize, Serialize};
use serde_json::Value;

// ─── JSON-RPC 2.0 base types ────────────────────────────────────────

/// Incoming JSON-RPC request (may be a notification if id is None)
#[derive(Deserialize, Debug)]
pub struct JsonRpcRequest {
    #[allow(dead_code)]
    pub jsonrpc: String,
    pub id: Option<Value>,
    pub method: String,
    #[serde(default)]
    pub params: Option<Value>,
}

/// Outgoing JSON-RPC response
#[derive(Serialize, Debug)]
pub struct JsonRpcResponse {
    pub jsonrpc: String,
    pub id: Value,
    pub result: Value,
}

/// Outgoing JSON-RPC error response
#[derive(Serialize, Debug)]
pub struct JsonRpcErrorResponse {
    pub jsonrpc: String,
    pub id: Value,
    pub error: JsonRpcError,
}

#[derive(Serialize, Debug)]
pub struct JsonRpcError {
    pub code: i64,
    pub message: String,
}

// ─── MCP Initialize types ───────────────────────────────────────────

#[derive(Serialize, Debug)]
pub struct InitializeResult {
    #[serde(rename = "protocolVersion")]
    pub protocol_version: String,
    pub capabilities: ServerCapabilities,
    #[serde(rename = "serverInfo")]
    pub server_info: ServerInfo,
    /// MCP server-level instructions for LLM clients.
    /// Provides best practices and tool selection guidance.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
}

#[derive(Serialize, Debug)]
pub struct ServerCapabilities {
    pub tools: ToolsCapability,
}

#[derive(Serialize, Debug)]
pub struct ToolsCapability {
    #[serde(rename = "listChanged")]
    pub list_changed: bool,
}

#[derive(Serialize, Debug)]
pub struct ServerInfo {
    pub name: String,
    pub version: String,
}

// ─── MCP Tools types ────────────────────────────────────────────────

#[derive(Serialize, Debug)]
pub struct ToolsListResult {
    pub tools: Vec<ToolDefinition>,
}

#[derive(Serialize, Debug, Clone)]
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    #[serde(rename = "inputSchema")]
    pub input_schema: Value,
}

/// MCP tool call result content
#[derive(Serialize, Debug)]
pub struct ToolCallResult {
    pub content: Vec<ToolContent>,
    #[serde(rename = "isError", skip_serializing_if = "std::ops::Not::not")]
    pub is_error: bool,
}

#[derive(Serialize, Debug)]
pub struct ToolContent {
    #[serde(rename = "type")]
    pub content_type: String,
    pub text: String,
}

// ─── Helper constructors ────────────────────────────────────────────

impl JsonRpcResponse {
    pub fn new(id: Value, result: Value) -> Self {
        Self {
            jsonrpc: "2.0".to_string(),
            id,
            result,
        }
    }
}

impl JsonRpcErrorResponse {
    pub fn new(id: Value, code: i64, message: String) -> Self {
        Self {
            jsonrpc: "2.0".to_string(),
            id,
            error: JsonRpcError { code, message },
        }
    }
}

impl ToolCallResult {
    pub fn success(text: String) -> Self {
        Self {
            content: vec![ToolContent {
                content_type: "text".to_string(),
                text,
            }],
            is_error: false,
        }
    }

    pub fn error(text: String) -> Self {
        Self {
            content: vec![ToolContent {
                content_type: "text".to_string(),
                text,
            }],
            is_error: true,
        }
    }
}

impl InitializeResult {
    /// Create a new InitializeResult with dynamic instructions.
    ///
    /// `def_extensions` — the file extensions that have definition parser support
    /// in the current server configuration (intersection of --ext and DEFINITION_EXTENSIONS).
    pub fn new(def_extensions: &[&str]) -> Self {
        Self {
            protocol_version: "2025-03-26".to_string(),
            capabilities: ServerCapabilities {
                tools: ToolsCapability {
                    list_changed: false,
                },
            },
            server_info: ServerInfo {
                name: "search-index".to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
            },
            instructions: Some(crate::tips::render_instructions(def_extensions)),
        }
    }

    // Instructions text is generated by crate::tips::render_instructions().
    // Note: CLI `search tips` uses render_cli() and MCP `search_help` uses render_json() —
    // each renderer is tailored to its audience (machine vs human vs on-demand reference).
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_initialize_request() {
        let json = r#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"test","version":"1.0"}}}"#;
        let req: JsonRpcRequest = serde_json::from_str(json).unwrap();
        assert_eq!(req.method, "initialize");
        assert_eq!(req.id, Some(serde_json::json!(1)));
        assert!(req.params.is_some());
    }

    #[test]
    fn test_parse_notification() {
        let json = r#"{"jsonrpc":"2.0","method":"notifications/initialized"}"#;
        let req: JsonRpcRequest = serde_json::from_str(json).unwrap();
        assert_eq!(req.method, "notifications/initialized");
        assert!(req.id.is_none());
    }

    #[test]
    fn test_parse_tools_list_request() {
        let json = r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#;
        let req: JsonRpcRequest = serde_json::from_str(json).unwrap();
        assert_eq!(req.method, "tools/list");
        assert_eq!(req.id, Some(serde_json::json!(2)));
    }

    #[test]
    fn test_parse_tools_call_request() {
        let json = r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"search_grep","arguments":{"terms":"HttpClient","mode":"or"}}}"#;
        let req: JsonRpcRequest = serde_json::from_str(json).unwrap();
        assert_eq!(req.method, "tools/call");
        let params = req.params.unwrap();
        assert_eq!(params["name"], "search_grep");
        assert_eq!(params["arguments"]["terms"], "HttpClient");
        assert_eq!(params["arguments"]["mode"], "or");
    }

    #[test]
    fn test_initialize_response_format() {
        let result = InitializeResult::new(crate::definitions::DEFINITION_EXTENSIONS);
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(json["protocolVersion"], "2025-03-26");
        assert_eq!(json["capabilities"]["tools"]["listChanged"], false);
        assert_eq!(json["serverInfo"]["name"], "search-index");
        assert_eq!(json["serverInfo"]["version"], env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn test_initialize_includes_instructions() {
        let result = InitializeResult::new(crate::definitions::DEFINITION_EXTENSIONS);
        let json = serde_json::to_value(&result).unwrap();
        let instructions = json["instructions"].as_str().unwrap();
        assert!(instructions.contains("search_fast"), "instructions should mention search_fast");
        assert!(instructions.contains("search_find"), "instructions should mention search_find");
        assert!(instructions.contains("substring"), "instructions should mention substring search");
        assert!(instructions.contains("search_callers"), "instructions should mention search_callers");
        assert!(instructions.contains("class"), "instructions should mention class parameter");
        assert!(instructions.contains("includeBody"), "instructions should mention includeBody");
        assert!(instructions.contains("countOnly"), "instructions should mention countOnly");
        // Verify all definition extensions appear in instructions
        for ext in crate::definitions::DEFINITION_EXTENSIONS {
            assert!(instructions.contains(&format!(".{}", ext)),
                "instructions should mention .{} extension", ext);
        }
    }

    #[test]
    fn test_jsonrpc_response_format() {
        let resp = JsonRpcResponse::new(
            serde_json::json!(1),
            serde_json::to_value(InitializeResult::new(crate::definitions::DEFINITION_EXTENSIONS)).unwrap(),
        );
        let json = serde_json::to_string(&resp).unwrap();
        let parsed: Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed["jsonrpc"], "2.0");
        assert_eq!(parsed["id"], 1);
        assert!(parsed["result"]["protocolVersion"].is_string());
    }

    #[test]
    fn test_tool_call_success_result() {
        let result = ToolCallResult::success("hello".to_string());
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(json["content"][0]["type"], "text");
        assert_eq!(json["content"][0]["text"], "hello");
        // isError should not appear when false
        assert!(json.get("isError").is_none());
    }

    #[test]
    fn test_tool_call_error_result() {
        let result = ToolCallResult::error("something failed".to_string());
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(json["content"][0]["text"], "something failed");
        assert_eq!(json["isError"], true);
    }

    #[test]
    fn test_jsonrpc_error_response() {
        let resp = JsonRpcErrorResponse::new(
            serde_json::json!(5),
            -32601,
            "Method not found".to_string(),
        );
        let json = serde_json::to_value(&resp).unwrap();
        assert_eq!(json["jsonrpc"], "2.0");
        assert_eq!(json["id"], 5);
        assert_eq!(json["error"]["code"], -32601);
        assert_eq!(json["error"]["message"], "Method not found");
    }
}